name: Python Django Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    SECRET_KEY: ${{ secrets.SECRET_KEY }}
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt
      - name: print variable
        run: |
          echo "SECRET_KEY is ${SECRET_KEY}"
      - name: Test
        run: |
          python manage.py migrate
          pytest
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0
      - name: Merge
        run: |
          git config --global user.name "${{ github.repository_owner }}"
          git config --global user.email "aseel.ashraf@icloud.com"
          git fetch origin pull/${{ github.event.pull_request.number }}/merge --no-tags --no-recurse-submodules
          git merge FETCH_HEAD -m "Merge pull request #${{ github.event.pull_request.number }}"

      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
