name: Python Django Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt
      - name: print variable
        run: |
          echo "SECRET_KEY is ${SECRET_KEY}"
      - name: Test
        run: |
          python manage.py migrate
          pytest
